### ISSUE TITLE
Bug when attempting on new OS install

### ISSUE THREAD

**Issue by ShinobiHanzo** [htrgouvea/spellbook#81]
**Inability to launch after building deps**

tried running the build on a new install of kali-linux and I can't seem to get it working.

continues to respond with the following:
##
Can't locate Find/Lib.pm in @INC (you may need to install the Find::Lib module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at ./spellbook.pl line 6.
BEGIN failed--compilation aborted at ./spellbook.pl line 6.
##

**To Reproduce**

1. install new kali-linux
2. same steps as shown in "README.md"
3. error

**Expected behavior**

to be able to find the lib in the local folder regardless

**Screenshots**

![image](https://github.com/htrgouvea/spellbook/assets/81740616/64f3289c-e770-4bbd-a658-6a95a4a97b5e)

**Desktop (please complete the following information):**

 - OS: [ Linux kali 6.5.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09) x86_64 GNU/Linux ]
 - Version [ v6.5.6 ]

**Additional context**

N/A

**Comment by htrgouvea** [comment]
Hi @ShinobiHanzo, try this command please:

$ sudo cpan install Find::Lib

Find::Lib is a dependency library of spellbook and this command do the setup.

Thanks.
